services:
  app:
    build: .
    environment:
      DB_HOST: localhost
      DB_PORT: "3306"
      DB_USER: bubble_community
      DB_PASSWORD: "xp3jEFdc5HsZKC7H"
      DB_NAME: bubble_community
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8001:8001"
