CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  author_name VARCHAR(32) NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bubbles (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NULL,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(120) NOT NULL DEFAULT '',
  svg_template MEDIUMTEXT NOT NULL,
  color VARCHAR(32) NOT NULL DEFAULT '',
  text_color VARCHAR(32) NOT NULL DEFAULT '',
  is_public TINYINT(1) NOT NULL DEFAULT 0,
  is_official TINYINT(1) NOT NULL DEFAULT 0,
  share_code VARCHAR(32) NULL UNIQUE,
  author_name VARCHAR(32) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_bubbles_user (user_id),
  INDEX idx_bubbles_public (is_public),
  INDEX idx_bubbles_official (is_official)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_current_bubble (
  user_id BIGINT PRIMARY KEY,
  bubble_id BIGINT NOT NULL,
  set_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS imported_bubbles (
  user_id BIGINT NOT NULL,
  bubble_id BIGINT NOT NULL,
  imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, bubble_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_favorites (
  user_id BIGINT NOT NULL,
  bubble_id BIGINT NOT NULL,
  favorited_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, bubble_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;